name: Update foundry-bin

on:
  workflow_dispatch:
  schedule:
  - cron: '6 9 * * *' # Run daily

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Building package
        run: 'cd ./foundry-bin && ./update.sh'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'foundry-bin/releases.nix: Nightly update'
